{
    "docs": "https://docs.ansible.com/ansible/devel/dev_guide/testing/sanity/symlinks.html", 
    "results": [
        {
            "message": "The test `ansible-test sanity --test symlinks` [[explain](https://docs.ansible.com/ansible/devel/dev_guide/testing/sanity/symlinks.html)] failed with 4 errors:", 
            "output": "tests/output/.tmp/delegation/python3.7/bin/python:0:0: symlinks outside content tree are not allowed: ../../../../../../../../../../../../../usr/bin/python3.7\ntests/output/.tmp/delegation/python3.7/bin/python3:0:0: symlinks outside content tree are not allowed: ../../../../../../../../../../../../../usr/bin/python3.7\ntests/output/.tmp/delegation/python3.7/bin/python3.7:0:0: symlinks outside content tree are not allowed: ../../../../../../../../../../../../../usr/bin/python3.7\ntests/output/.tmp/delegation/python3.7/lib64/:0:0: symlinks to directories are not allowed"
        }
    ], 
    "verified": false
}
